# -*- coding: utf-8 -*-
"""KGCN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GQ6mUgkIeGLLOtLJeuVuJA4KI_jKBI5
"""

import pandas as pd
import torch
from torch_geometric.data import Data
from itertools import combinations
import random
import numpy as np
import json

from pymongo import MongoClient
# connect to MongoDB
client = MongoClient("mongodb+srv://cinemaniacs:filmlytics@filmlytics.1emhcue.mongodb.net/?appName=filmlytics")
db = client.cinemaniacs
movies = db.movies
# query all movies
data = list(movies.find({}))
df = pd.DataFrame(data)

# clean nested fields
def safe_get(d, key, default=None):
    if isinstance(d, dict) and key in d:
        return d[key]
    return default

# parse genres
df["genres_list"] = df["production"].apply(
    lambda x: safe_get(x, "genres", []) if isinstance(x, dict) else []
)

# numeric features
df["budget"] = df["production"].apply(lambda x: safe_get(x, "budget", 0))
df["runtime"] = df["production"].apply(lambda x: safe_get(x, "runtime", 0))
df["vote_count"] = df["tmdb_metrics"].apply(lambda x: safe_get(x, "vote_count", 0))
df["vote_average"] = df["tmdb_metrics"].apply(lambda x: safe_get(x, "vote_average", 0))
df["is_successful"] = df["tmdb_metrics"].apply(lambda x: safe_get(x, "is_successful", 0))

df["critic_score"] = df["rotten_tomatoes"].apply(lambda x: safe_get(x, "critic_score", 0))
df["audience_score"] = df["rotten_tomatoes"].apply(lambda x: safe_get(x, "audience_score", 0))

df["description_sentiment_score"] = df["sentiment"].apply(
    lambda x: safe_get(x, "description_sentiment_score", 0)
)

num_features = [
    "budget",
    "runtime",
    "vote_count",
    "vote_average",
    "is_successful",
    "critic_score",
    "audience_score",
    "description_sentiment_score",
]

# convert to numeric
for f in num_features:
    df[f] = pd.to_numeric(df[f], errors="coerce").fillna(0)

# list of movie indices with mapping genre
genre_to_movies = {}

for idx, genres in df["genres_list"].items():
    for g in genres:
        genre_to_movies.setdefault(g, []).append(idx)

edge_dict = {}
MAX_EDGES_PER_GENRE = 2000

for genre, movies in genre_to_movies.items():

    # reservoir sampling to avoid loading all pairs into memory
    selected_pairs = []
    count = 0

    for i, j in combinations(movies, 2):
        count += 1
        if len(selected_pairs) < MAX_EDGES_PER_GENRE:
            selected_pairs.append((i, j))
        else:
            r = random.randint(1, count)
            if r <= MAX_EDGES_PER_GENRE:
                selected_pairs[r-1] = (i, j)

    # add selected pairs to edge_dict
    for i, j in selected_pairs:

        # canonical ordering
        if i > j:
            i, j = j, i

        edge_dict[(i, j)] = edge_dict.get((i, j), 0) + 1

MAX_EDGES = 5000

edge_list = [(i, j, w) for (i, j), w in edge_dict.items()]
edge_list = sorted(edge_list, key=lambda x: x[2], reverse=True)[:MAX_EDGES]

edge_index = torch.tensor([[i, j] for (i, j, w) in edge_list], dtype=torch.long).T
edge_attr  = torch.tensor([w for (i, j, w) in edge_list], dtype=torch.float).unsqueeze(1)

x = torch.tensor(df[num_features].values, dtype=torch.float)

y = torch.tensor(df["audience_score"].values, dtype=torch.float)

data = Data(
    x=x,
    edge_index=edge_index,
    edge_attr=edge_attr,
    y=y
)

print(data)
print("Nodes:", data.num_nodes)
print("Edges:", data.num_edges)
print("Feature dim:", data.num_node_features)
print("Edge attr dim:", data.edge_attr.size(1))

# build NetworkX graph using row index as node ids
import networkx as nx
from itertools import combinations
import pandas as pd
import random
import heapq

G = nx.Graph()

# add all movie nodes
for idx, row in df.iterrows():

    movie_id = int(idx)                  # internal graph id
    tmdb_id = row.get("tmdb_id", None)

    G.add_node(movie_id)

    # store tmdb_id
    G.nodes[movie_id]["tmdb_id"] = tmdb_id

    # title block
    G.nodes[movie_id]["title"] = row.get("title", "")

    # production block
    prod = row.get("production", {}) or {}
    G.nodes[movie_id]["budget"] = prod.get("budget", None)
    G.nodes[movie_id]["runtime"] = prod.get("runtime", None)
    G.nodes[movie_id]["genres"] = prod.get("genres", [])
    G.nodes[movie_id]["production_companies"] = prod.get("production_companies", [])
    G.nodes[movie_id]["production_countries"] = prod.get("production_countries", [])

    # people block
    ppl = row.get("people", {}) or {}
    G.nodes[movie_id]["cast"] = ppl.get("cast", [])
    G.nodes[movie_id]["directors"] = ppl.get("directors", [])

    # TMDB metrics block
    met = row.get("tmdb_metrics", {}) or {}
    G.nodes[movie_id]["vote_count"] = met.get("vote_count", None)
    G.nodes[movie_id]["vote_average"] = met.get("vote_average", None)
    G.nodes[movie_id]["is_successful"] = met.get("is_successful", None)

    # Rotten Tomatoes block
    rt = row.get("rotten_tomatoes", {}) or {}
    G.nodes[movie_id]["critic_score"] = rt.get("critic_score", None)
    G.nodes[movie_id]["audience_score"] = rt.get("audience_score", None)
    G.nodes[movie_id]["review_sentiment"] = rt.get("review_sentiment", None)


# build edges using genres
genre_to_movies = {}

for idx, row in df.iterrows():

    movie_id = int(idx)
    prod = row.get("production", {}) or {}
    genres = prod.get("genres", [])

    for g in genres:
        genre_to_movies.setdefault(g, []).append(movie_id)


# create weighted "shared-genre" edges
edge_counter = {}
MAX_GENRE_SIZE = 1500   # prevents memory explosion

# streaming top-k heap: (weight, m1, m2)
heap = []
MAX_EDGES = 5000

for genre, movies_in_genre in genre_to_movies.items():

    movies = movies_in_genre

    # subsample huge genres
    if len(movies) > MAX_GENRE_SIZE:
        movies = random.sample(movies, MAX_GENRE_SIZE)

    for m1, m2 in combinations(movies, 2):

        # canonical ordering for dictionary key
        if m1 > m2:
            m1, m2 = m2, m1

        # update local edge weight
        w = edge_counter.get((m1, m2), 0) + 1
        edge_counter[(m1, m2)] = w

        # push into heap or replace smallest
        if len(heap) < MAX_EDGES:
            heapq.heappush(heap, (w, m1, m2))
        else:
            if w > heap[0][0]:  # current edge is stronger than weakest in heap
                heapq.heapreplace(heap, (w, m1, m2))


# limit to max 5000 strongest edges
limited_edges = heapq.nlargest(MAX_EDGES, heap)

for w, u, v in limited_edges:
    G.add_edge(u, v, weight=w)


print("NetworkX Graph Ready")
print("Nodes:", G.number_of_nodes())
print("Edges:", G.number_of_edges())

from torch_geometric.utils import from_networkx

numeric_attrs = [
    "budget", "runtime",
    "vote_count", "vote_average",
    "critic_score", "audience_score"
]

# ensure these attributes exist and are numeric
for n in G.nodes:
    for key in numeric_attrs:
        val = G.nodes[n].get(key, 0)

        # replace None or list/dict with 0
        if val is None or isinstance(val, (list, dict)):
            G.nodes[n][key] = 0.0
        else:
            # force cast to float
            try:
                G.nodes[n][key] = float(val)
            except:
                G.nodes[n][key] = 0.0

# now convert
data = from_networkx(G, group_node_attrs=numeric_attrs)

print(data)
print("Nodes:", data.num_nodes)
print("Edges:", data.num_edges)
print("Feature dim:", data.num_node_features)

# Subgraph of high-degree nodes
import matplotlib.pyplot as plt
degrees = dict(G.degree())
top = sorted(degrees, key=degrees.get, reverse=True)[:1000]

H = G.subgraph(top)

plt.figure(figsize=(8,8))
nx.draw(H, node_size=20)
plt.show()

genre = "Family"
nodes = [n for n in G.nodes if genre in G.nodes[n]["genres"]]
H = G.subgraph(nodes[:200])

nx.draw(H, node_size=20)
plt.show()